// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: spn/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetTestnetStateRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetTestnetStateRequest) Reset()         { *m = QueryGetTestnetStateRequest{} }
func (m *QueryGetTestnetStateRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetTestnetStateRequest) ProtoMessage()    {}
func (*QueryGetTestnetStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91287b43b51aa11c, []int{0}
}
func (m *QueryGetTestnetStateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTestnetStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTestnetStateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTestnetStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTestnetStateRequest.Merge(m, src)
}
func (m *QueryGetTestnetStateRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTestnetStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTestnetStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTestnetStateRequest proto.InternalMessageInfo

func (m *QueryGetTestnetStateRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetTestnetStateResponse struct {
	TestnetState *TestnetState `protobuf:"bytes,1,opt,name=TestnetState,proto3" json:"TestnetState,omitempty"`
}

func (m *QueryGetTestnetStateResponse) Reset()         { *m = QueryGetTestnetStateResponse{} }
func (m *QueryGetTestnetStateResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetTestnetStateResponse) ProtoMessage()    {}
func (*QueryGetTestnetStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91287b43b51aa11c, []int{1}
}
func (m *QueryGetTestnetStateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTestnetStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTestnetStateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTestnetStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTestnetStateResponse.Merge(m, src)
}
func (m *QueryGetTestnetStateResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTestnetStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTestnetStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTestnetStateResponse proto.InternalMessageInfo

func (m *QueryGetTestnetStateResponse) GetTestnetState() *TestnetState {
	if m != nil {
		return m.TestnetState
	}
	return nil
}

type QueryAllTestnetStateRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllTestnetStateRequest) Reset()         { *m = QueryAllTestnetStateRequest{} }
func (m *QueryAllTestnetStateRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllTestnetStateRequest) ProtoMessage()    {}
func (*QueryAllTestnetStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91287b43b51aa11c, []int{2}
}
func (m *QueryAllTestnetStateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllTestnetStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllTestnetStateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllTestnetStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllTestnetStateRequest.Merge(m, src)
}
func (m *QueryAllTestnetStateRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllTestnetStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllTestnetStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllTestnetStateRequest proto.InternalMessageInfo

func (m *QueryAllTestnetStateRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllTestnetStateResponse struct {
	TestnetState []*TestnetState     `protobuf:"bytes,1,rep,name=TestnetState,proto3" json:"TestnetState,omitempty"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllTestnetStateResponse) Reset()         { *m = QueryAllTestnetStateResponse{} }
func (m *QueryAllTestnetStateResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllTestnetStateResponse) ProtoMessage()    {}
func (*QueryAllTestnetStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91287b43b51aa11c, []int{3}
}
func (m *QueryAllTestnetStateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllTestnetStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllTestnetStateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllTestnetStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllTestnetStateResponse.Merge(m, src)
}
func (m *QueryAllTestnetStateResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllTestnetStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllTestnetStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllTestnetStateResponse proto.InternalMessageInfo

func (m *QueryAllTestnetStateResponse) GetTestnetState() []*TestnetState {
	if m != nil {
		return m.TestnetState
	}
	return nil
}

func (m *QueryAllTestnetStateResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetTestnetStateRequest)(nil), "lubtd.ibclab.spn.QueryGetTestnetStateRequest")
	proto.RegisterType((*QueryGetTestnetStateResponse)(nil), "lubtd.ibclab.spn.QueryGetTestnetStateResponse")
	proto.RegisterType((*QueryAllTestnetStateRequest)(nil), "lubtd.ibclab.spn.QueryAllTestnetStateRequest")
	proto.RegisterType((*QueryAllTestnetStateResponse)(nil), "lubtd.ibclab.spn.QueryAllTestnetStateResponse")
}

func init() { proto.RegisterFile("spn/query.proto", fileDescriptor_91287b43b51aa11c) }

var fileDescriptor_91287b43b51aa11c = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x31, 0x6b, 0x1b, 0x31,
	0x14, 0x80, 0x2d, 0x17, 0x17, 0xaa, 0x16, 0x5c, 0x44, 0x29, 0xc5, 0x35, 0xc2, 0x5c, 0xc1, 0x35,
	0x85, 0x4a, 0xd8, 0x9e, 0x3b, 0xd8, 0x43, 0xbd, 0xb6, 0x4e, 0xa6, 0x6c, 0x92, 0x2d, 0x2e, 0x07,
	0x67, 0xe9, 0x6c, 0xe9, 0x82, 0x4d, 0xc8, 0x92, 0x5f, 0x10, 0xc8, 0x92, 0x25, 0xbf, 0x20, 0xff,
	0x22, 0x53, 0x46, 0x43, 0x96, 0x8c, 0xc1, 0xce, 0x0f, 0x09, 0x96, 0x2e, 0xe4, 0xce, 0xf6, 0x39,
	0xc9, 0x78, 0xba, 0xf7, 0xbd, 0xf7, 0xbd, 0xf7, 0x24, 0x58, 0xd6, 0x91, 0xa4, 0xe3, 0x58, 0x4c,
	0x66, 0x24, 0x9a, 0x28, 0xa3, 0xd0, 0xe7, 0x30, 0xe6, 0x66, 0x48, 0x02, 0x3e, 0x08, 0x19, 0x27,
	0x3a, 0x92, 0x95, 0xaa, 0xaf, 0x94, 0x1f, 0x0a, 0xca, 0xa2, 0x80, 0x32, 0x29, 0x95, 0x61, 0x26,
	0x50, 0x52, 0xbb, 0xf8, 0xca, 0xaf, 0x81, 0xd2, 0x23, 0xa5, 0x29, 0x67, 0x5a, 0xb8, 0x44, 0xf4,
	0xa8, 0xc9, 0x85, 0x61, 0x4d, 0x1a, 0x31, 0x3f, 0x90, 0x36, 0x38, 0x89, 0xfd, 0xba, 0x2a, 0x66,
	0x84, 0x36, 0x52, 0x98, 0x3d, 0xc3, 0x8c, 0x70, 0xe7, 0x5e, 0x1b, 0x7e, 0xff, 0xbf, 0x22, 0x7b,
	0xc2, 0xec, 0xa7, 0xfe, 0xf6, 0xc5, 0x38, 0x16, 0xda, 0xa0, 0x2f, 0xb0, 0x14, 0xc8, 0xa1, 0x98,
	0x7e, 0x03, 0x35, 0xd0, 0xf8, 0xd0, 0x77, 0x1f, 0x1e, 0x87, 0xd5, 0xed, 0x90, 0x8e, 0x94, 0xd4,
	0x02, 0x75, 0xe1, 0xa7, 0xf4, 0xb9, 0x85, 0x3f, 0xb6, 0x30, 0x59, 0xef, 0x8f, 0x64, 0xe8, 0x0c,
	0xe3, 0x89, 0x44, 0xac, 0x13, 0x86, 0xdb, 0xc4, 0xfe, 0x42, 0xf8, 0xdc, 0x63, 0x52, 0xa0, 0x4e,
	0xdc, 0x40, 0xc8, 0x6a, 0x20, 0xc4, 0x4d, 0x36, 0x19, 0x08, 0xf9, 0xc7, 0xfc, 0x27, 0xb6, 0x9f,
	0x22, 0xbd, 0x2b, 0x90, 0xf4, 0xb2, 0x51, 0x27, 0xb7, 0x97, 0x77, 0x6f, 0xed, 0x05, 0xf5, 0x32,
	0xb2, 0x45, 0x2b, 0xfb, 0xf3, 0x45, 0x59, 0x27, 0x90, 0xb6, 0x6d, 0x5d, 0x17, 0x61, 0xc9, 0xda,
	0xa2, 0x4b, 0x90, 0xf5, 0x42, 0xbf, 0x37, 0x8d, 0x76, 0x2c, 0xb6, 0x42, 0x5e, 0x1b, 0xee, 0x2c,
	0x3c, 0x72, 0x7a, 0xfb, 0x70, 0x5e, 0x6c, 0xa0, 0x3a, 0xb5, 0x1c, 0x75, 0x1c, 0x5d, 0xbf, 0x55,
	0xf4, 0xd8, 0xde, 0x90, 0x13, 0x74, 0x01, 0x60, 0x39, 0x9d, 0xa8, 0x13, 0x86, 0xb9, 0x8a, 0xdb,
	0x57, 0x9c, 0xab, 0x98, 0xb3, 0x29, 0xaf, 0x6e, 0x15, 0x6b, 0x08, 0xef, 0x56, 0xec, 0xfe, 0xb9,
	0x59, 0x60, 0x30, 0x5f, 0x60, 0x70, 0xbf, 0xc0, 0xe0, 0x6c, 0x89, 0x0b, 0xf3, 0x25, 0x2e, 0xdc,
	0x2d, 0x71, 0xe1, 0xe0, 0x87, 0x1f, 0x98, 0xc3, 0x98, 0x93, 0x81, 0x1a, 0x65, 0x73, 0x4c, 0x5d,
	0x96, 0x59, 0x24, 0x34, 0x7f, 0x6f, 0x1f, 0x4e, 0xfb, 0x31, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x48,
	0xc7, 0x2b, 0xbf, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// this line is used by starport scaffolding # 2
	TestnetState(ctx context.Context, in *QueryGetTestnetStateRequest, opts ...grpc.CallOption) (*QueryGetTestnetStateResponse, error)
	TestnetStateAll(ctx context.Context, in *QueryAllTestnetStateRequest, opts ...grpc.CallOption) (*QueryAllTestnetStateResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) TestnetState(ctx context.Context, in *QueryGetTestnetStateRequest, opts ...grpc.CallOption) (*QueryGetTestnetStateResponse, error) {
	out := new(QueryGetTestnetStateResponse)
	err := c.cc.Invoke(ctx, "/lubtd.ibclab.spn.Query/TestnetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TestnetStateAll(ctx context.Context, in *QueryAllTestnetStateRequest, opts ...grpc.CallOption) (*QueryAllTestnetStateResponse, error) {
	out := new(QueryAllTestnetStateResponse)
	err := c.cc.Invoke(ctx, "/lubtd.ibclab.spn.Query/TestnetStateAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// this line is used by starport scaffolding # 2
	TestnetState(context.Context, *QueryGetTestnetStateRequest) (*QueryGetTestnetStateResponse, error)
	TestnetStateAll(context.Context, *QueryAllTestnetStateRequest) (*QueryAllTestnetStateResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) TestnetState(ctx context.Context, req *QueryGetTestnetStateRequest) (*QueryGetTestnetStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestnetState not implemented")
}
func (*UnimplementedQueryServer) TestnetStateAll(ctx context.Context, req *QueryAllTestnetStateRequest) (*QueryAllTestnetStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestnetStateAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_TestnetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetTestnetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TestnetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lubtd.ibclab.spn.Query/TestnetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TestnetState(ctx, req.(*QueryGetTestnetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TestnetStateAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllTestnetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TestnetStateAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lubtd.ibclab.spn.Query/TestnetStateAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TestnetStateAll(ctx, req.(*QueryAllTestnetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lubtd.ibclab.spn.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestnetState",
			Handler:    _Query_TestnetState_Handler,
		},
		{
			MethodName: "TestnetStateAll",
			Handler:    _Query_TestnetStateAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spn/query.proto",
}

func (m *QueryGetTestnetStateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTestnetStateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTestnetStateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetTestnetStateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTestnetStateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTestnetStateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TestnetState != nil {
		{
			size, err := m.TestnetState.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllTestnetStateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllTestnetStateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllTestnetStateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllTestnetStateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllTestnetStateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllTestnetStateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.TestnetState) > 0 {
		for iNdEx := len(m.TestnetState) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TestnetState[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetTestnetStateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetTestnetStateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TestnetState != nil {
		l = m.TestnetState.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllTestnetStateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllTestnetStateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TestnetState) > 0 {
		for _, e := range m.TestnetState {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetTestnetStateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTestnetStateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTestnetStateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTestnetStateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTestnetStateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTestnetStateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TestnetState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TestnetState == nil {
				m.TestnetState = &TestnetState{}
			}
			if err := m.TestnetState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllTestnetStateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllTestnetStateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllTestnetStateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllTestnetStateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllTestnetStateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllTestnetStateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TestnetState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TestnetState = append(m.TestnetState, &TestnetState{})
			if err := m.TestnetState[len(m.TestnetState)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
